### ISSUE TITLE
github tests?

### ISSUE THREAD

**Issue by microprediction** [OVVO-Financial/NNS-Python#17]
Hi I am a friend of Fred's. 

I created these GitHub actions. Feel free to copy them to NNS-Python if you wish

https://github.com/microprediction/timemachines/blob/main/.github/workflows/test-nns-github.yml
https://github.com/microprediction/timemachines/blob/main/.github/workflows/test-nns.yml

Peter

**Comment by rspadim** [comment]
I @microprediction sorry I was not looking issues here at github, i will check workflows for sure! I started but without time it's not working today, I made a "copy paste"  from uvicorn project (i like the black -l 100 style, autoflake + isort, but never used github ci/cd before)

well, i will read it and merge with time! thanks a lot! glad to see you here

**Comment by rspadim** [comment]
@microprediction could you help me creating the ci/cd here at github? it's mainly run the test of black/isort/autoflake, i don't know if it's possible to automate the pypi package deploy too, but could be nice if you know how to do it too

thanks!

**Comment by rspadim** [comment]
working on it https://github.com/OVVO-Financial/NNS-Python/blob/devel-spadim/.github/workflows/test-nns.yml

**Comment by microprediction** [comment]
Sure though I think I need to be a collaborator

**Comment by OVVO-Financial** [comment]
@microprediction collaborator invite sent!

**Comment by rspadim** [comment]
=) done
anyway i will leave py39 out while numba doesn't support it, and i will not change to cython in near time
https://github.com/OVVO-Financial/NNS-Python/runs/4808001814?check_suite_focus=true
